### ISSUE TITLE
List of list support

### ISSUE THREAD

**Issue by enzoferey** [Quramy/ts-graphql-plugin#124]
Hi, I just introduced for the first time a list of list type in my GraphQL schema, and I found out `ts-graphql-plugin` is not supporting it.

Visiting nodes seams to be hardcoded to a single nested level list looking at [_getFieldMetadataFromFieldTypeInstance](https://github.com/Quramy/ts-graphql-plugin/blob/719671c3eb8219a5fc2b221c143c2636d31055cb/src/typegen/type-gen-visitor.ts#L334), [_getFieldMetadataFromTypeNode](https://github.com/Quramy/ts-graphql-plugin/blob/719671c3eb8219a5fc2b221c143c2636d31055cb/src/typegen/type-gen-visitor.ts#L377), and [_wrapTsTypeNodeWithModifiers](https://github.com/Quramy/ts-graphql-plugin/blob/719671c3eb8219a5fc2b221c143c2636d31055cb/src/typegen/type-gen-visitor.ts#L424).

I have made a patch via `patch-package` for my use case --> `[[Type!]!]!`

```
diff --git a/node_modules/ts-graphql-plugin/lib/typegen/type-gen-visitor.js b/node_modules/ts-graphql-plugin/lib/typegen/type-gen-visitor.js
index 8fab69f..ca925f0 100644
--- a/node_modules/ts-graphql-plugin/lib/typegen/type-gen-visitor.js
+++ b/node_modules/ts-graphql-plugin/lib/typegen/type-gen-visitor.js
@@ -245,8 +245,17 @@ class TypeGenVisitor {
                 if (fieldType instanceof graphql_1.GraphQLNonNull) {
                     fieldType = fieldType.ofType;
                     isStrict = true;
-                }
-                else {
+                    if (fieldType instanceof graphql_1.GraphQLList) {
+                        fieldType = fieldType.ofType;
+                        listTypeKind = 'strictListStrictList';
+                        if (fieldType instanceof graphql_1.GraphQLNonNull) {
+                            fieldType = fieldType.ofType;
+                            isStrict = true;
+                        } else {
+                            isStrict = false;
+                        }
+                    }
+                } else {
                     isStrict = false;
                 }
             }
@@ -328,11 +337,14 @@ class TypeGenVisitor {
         if (!strict) {
             typeNode = typescript_1.default.createUnionTypeNode([typeNode, typescript_1.default.createKeywordTypeNode(typescript_1.default.SyntaxKind.NullKeyword)]);
         }
-        if (list === 'strictList' || list === 'nullableList') {
+        if (list === 'strictList' || list === 'nullableList' || list === "strictListStrictList") {
             typeNode = typescript_1.default.createArrayTypeNode(typeNode);
             if (list === 'nullableList') {
                 typeNode = typescript_1.default.createUnionTypeNode([typeNode, typescript_1.default.createKeywordTypeNode(typescript_1.default.SyntaxKind.NullKeyword)]);
             }
+            if(list === "strictListStrictList") {
+                typeNode = typescript_1.default.createArrayTypeNode(typeNode);
+            }
         }
         return typeNode;
     }
```

I didn't think too much about the other cases, but a similar approach could be taken to cover other missing permutations (`nullableListStrictList`, `nullableListNullableList`, `strictListNullableList`).

I think this should eventually be recursive, but I highly doubt there are many business cases beyond a 2 dimension array, so it might be a cheaper feature to implement for now and whoever will have the need in the future will be able to scratch her/his head around 😄

**Comment by Quramy** [comment]
I fixed it.

If you have 

```gql
            type Query {
              nullableNestedList: [[String]]
              strictNestedList: [[String!]!]!
            }
```

the following type is generated:

```ts
export type MyQuery = {
    nullableNestedList: ((string | null)[] | null)[] | null;
    strictNestedList: string[][];
};
```

**Comment by enzoferey** [comment]
That was fast, thank you 🙌🏻 Beautiful solution by the way 👌🏻
