### ISSUE TITLE
Substituting Template String

### ISSUE THREAD

**Issue by Quramy** [Quramy/ts-graphql-plugin#2]
Now, adapter can treat only NonSubstituting Template Strings.

```ts
const query = ` query { }`            // it works
const query = ` query { ${foo} }` // it does not work
```

My problem is : 
- How to treat substituting params (e.g. `${foo}` ).  For example, in `getSemanticDiagonistics`, is it right to ignore the parameters ?

**Comment by guncha** [comment]
Came here to report this, but you're way ahead of me. To answer your question, I think it's safe to ignore the params as they're themselves queries that are going to be checked when `getSemanticDiagonistics` is called on the files that they're in.
