### ISSUE TITLE
External/Global fragment sources

### ISSUE THREAD

**Issue by jasonkuhrt** [Quramy/ts-graphql-plugin#360]
When working with GraphQL Relay they have a system where all components in the app using `createContainerFragmen` generate graphql fragments for use in a so-called 	`QueryRenderer`.

But reference to these fragments is global. See example here:

https://relay.dev/docs/en/quick-start-guide

```ts
        query={graphql`
          query ViewerQuery {
            viewer {
              id
              ...TodoList_userTodoData   # <-- global frament here...
            }
          }
        `}
 
```

How can this be supported?

Also note @acao [recently blogged about new support for this](https://rikki.dev/vscode-graphql-lsp-0-3-0/#completion-for-implicit-fragments) in the GraphQL VSCode extension. Could be inspiration.

**Comment by Quramy** [comment]
Relay has it's own naming convention about importing fragments.  https://relay.dev/docs/en/quick-start-guide#using-fragments

>  As a convention, we name the fragment as '<ComponentFileName>_<propName>'

I'm wondering whether I should add Relay specific features.

**Comment by jasonkuhrt** [comment]
> I'm wondering whether I should add Relay specific features.

That would be pretty amazing :)

**Comment by jasonkuhrt** [comment]
Trid emitting relay typegen into node_modules but got this nextjs error:


![image](https://user-images.githubusercontent.com/284476/107902843-96353d80-6f15-11eb-922b-ef8f5524684e.png)

It doesn't seem to like importing ESM from modules under node_modules.

**Comment by Quramy** [comment]
Introduce global fragment registry by #1209
