### ISSUE TITLE
schema not found error

### ISSUE THREAD

**Issue by jmolero** [Quramy/ts-graphql-plugin#86]
I get no completion or diagnostics. I tried also running this command but I get the following error:

```
$> npx ts-graphql-plugin validate -p tsconfig.server.json
Error: No GraphQL schema. Confirm your ts-graphql-plugin's "schema" configuration at tsconfig.json's compilerOptions.plugins section.
```

These are my tsconfg.server.json plugin settings:

```
    "plugins": [
      {
        "name": "ts-graphql-plugin",
        "schema": "./graphql/admin-api-schema.json",
        "tag": "gql"
      }
    ]
```

The same schema works with eslint-plugin-graphql though.

**Comment by Quramy** [comment]
@jmolero 

> I get no completion or diagnostics.

First, IDEs/editors (e.g. VS code) generally  don't read `tsconfig.server.json`. By default they read `tsconfig.json`.  

Second, about `Error: No GraphQL schema.` , please check your schema file. If you use a JSON file as schema, the JSON file should have the following format:

```js
{
  "data": {
    "__schema": {
      "queryType": {
        "name": "Query"
      },
      "types": [
        {
          "kind": "OBJECT",
          "name": "Query",
          "description": null,
          "fields": [
            {
              "name": "viewer",
              :
```

It should equal to result of introspection query for your API.


And `npx ts-graphql-plugin validate --verbose` may output more details.

**Comment by jmolero** [comment]
I missed the verbose option and it did help to find issue. My schema wasn't starting with the "data" field. 

After that, the validation command was working, but I also moved the plugin settings to `tsconfig.json` from `tsconfig.server.jsson` to make it work with inside neovim too. 

Thank you for the fast response!
