### ISSUE TITLE
ts-graphql-plugin not working with schema.json generated by apollo client CLI

### ISSUE THREAD

**Issue by Nnoerregaard** [Quramy/ts-graphql-plugin#96]
**Describe the bug**
If I run apollo client:download-schema from the apollo CLI (https://github.com/apollographql/apollo-tooling, version 2.6.8) and pass along the path to the generated schema.json file in the configuration of ts-graphql-plugin, no autocompletion occurs.

Inspecting the log from my tsserver reveals that the initialization of ts-graphql-plugin fails with the error "Could not read __schema of undefined". 

Wrapping the content of the generated schema.json file in "data": { }, as outlined in the README file fixes the issue.

**To Reproduce**
1) Install apollo client version 2.6.8 and run apollo client:download-schema with against your graphql endpoint to obtain a schema.json file containing your graphql schema.
2) Configure ts-graphql-plugin as outlined in the README file and make the schema point to the newly generated schema.json
3) (Re)start your editor. Attempt to trigger auto-completion in a gql string and notice how nothing happens
4) Open the log of your tsserver, search for [ts-graphql-plugin and notice how it reports the above-described error.
5) Wrap the content of graphql schema in data: { }, restart your editor and notice how auto-completion now works

**Expected behavior**
I except the plugin to work with the schema file output by apollo client by default without any modifications necessary as apollo is one of the big players in the graphql area. 

At the very least, I would like to be able to pass along a flag to ts-graphql-plugin when setting it up, informing it that it should interpret the schema.json file as the output of apollo client

**Debug log**
![Screenshot 2020-02-13 at 13 18 30](https://user-images.githubusercontent.com/6885285/74439056-64e9e380-4e63-11ea-8516-4f166a399a9f.png)

**Comment by Quramy** [comment]
ummm, this behavior is in my plugin spec. But similar issues( #86 ) have been reported. 
So, and as you say, I’ll consider into making it accept the schema json format.
