### ISSUE TITLE
should depend on/use graphql-language-service instead of graphql-language-service-interface (deprecated)

### ISSUE THREAD

**Issue by devkral** [Quramy/ts-graphql-plugin#984]
graphql-language-service-interface is now deprecated, the way to go is to use graphql-language-service
as all of the subpackages are merged into it.

see deprecation message

**Comment by kevinbarabash** [comment]
One feature that I'm excited about that's in `graphql-language-service` is `getAutocompleteSuggestions` includes documentation in the completion items it returns.  Currently `ts-graphql-plugin` only includes the names of the completions.  You can only access the documentation by hover over a field or whatever after you the completion has been inserted.
